
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Sanitasi Sumsels      <small><?= cclang('detail', ['Sanitasi Sumsels']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/sanitasi_sumsels'); ?>">Sanitasi Sumsels</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Sanitasi Sumsels</h3>
                     <h5 class="widget-user-desc">Detail Sanitasi Sumsels</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_sanitasi_sumsels" id="form_sanitasi_sumsels" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Sanitasi Sumsel </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->kode_sanitasi_sumsel); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Air Bersih Id </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->air_bersih_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kabupaten Kota </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->kabupaten_kota); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Wilayah </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->kode_wilayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->kode_kecamatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Text Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->text_kecamatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Luas </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->luas); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sanitasi </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->sanitasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Air Bersih </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->air_bersih); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kk Mbr </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->kk_mbr); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kk Nonmbr </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->kk_nonmbr); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Perkebunan </label>

                        <div class="col-sm-8">
                           <?= _ent($sanitasi_sumsels->perkebunan); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('sanitasi_sumsels_update', function() use ($sanitasi_sumsels){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit sanitasi_sumsels (Ctrl+e)" href="<?= site_url('administrator/sanitasi_sumsels/edit/'.$sanitasi_sumsels->kode_sanitasi_sumsel); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Sanitasi Sumsels']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/sanitasi_sumsels/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Sanitasi Sumsels']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
