
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Tol Ln 2017 Sumatera Selatan Pubtr Geo      <small><?= cclang('detail', ['Tol Ln 2017 Sumatera Selatan Pubtr Geo']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tol_ln_2017_sumatera_selatan_pubtr_geo'); ?>">Tol Ln 2017 Sumatera Selatan Pubtr Geo</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tol Ln 2017 Sumatera Selatan Pubtr Geo</h3>
                     <h5 class="widget-user-desc">Detail Tol Ln 2017 Sumatera Selatan Pubtr Geo</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tol_ln_2017_sumatera_selatan_pubtr_geo" id="form_tol_ln_2017_sumatera_selatan_pubtr_geo" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Stln </label>

                        <div class="col-sm-8">
                           <?= _ent($tol_ln_2017_sumatera_selatan_pubtr_geo->kode_stln); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tol Ln 2017 Sumatera Selatan Pubtr Geo Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tol_ln_2017_sumatera_selatan_pubtr_geo->tol_ln_2017_sumatera_selatan_pubtr_geo_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jalanrencana </label>

                        <div class="col-sm-8">
                           <?= _ent($tol_ln_2017_sumatera_selatan_pubtr_geo->jalanrencana); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ruas </label>

                        <div class="col-sm-8">
                           <?= _ent($tol_ln_2017_sumatera_selatan_pubtr_geo->ruas); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Tol </label>

                        <div class="col-sm-8">
                           <?= _ent($tol_ln_2017_sumatera_selatan_pubtr_geo->status_tol); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pemilik </label>

                        <div class="col-sm-8">
                           <?= _ent($tol_ln_2017_sumatera_selatan_pubtr_geo->pemilik); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tol_ln_2017_sumatera_selatan_pubtr_geo_update', function() use ($tol_ln_2017_sumatera_selatan_pubtr_geo){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tol_ln_2017_sumatera_selatan_pubtr_geo (Ctrl+e)" href="<?= site_url('administrator/tol_ln_2017_sumatera_selatan_pubtr_geo/edit/'.$tol_ln_2017_sumatera_selatan_pubtr_geo->kode_stln); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tol Ln 2017 Sumatera Selatan Pubtr Geo']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tol_ln_2017_sumatera_selatan_pubtr_geo/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tol Ln 2017 Sumatera Selatan Pubtr Geo']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
