
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Sungais      <small><?= cclang('detail', ['Sungais']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/sungais'); ?>">Sungais</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Sungais</h3>
                     <h5 class="widget-user-desc">Detail Sungais</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_sungais" id="form_sungais" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Sungai </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->kode_sungai); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sungai Id </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->sungai_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Fnode  </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->fnode_); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tnode </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->tnode); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lpoly  </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->lpoly_); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Length </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->length); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sungai  </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->sungai_); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Saluran </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->saluran); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Text Sungai </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->text_sungai); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Klasifikasi </label>

                        <div class="col-sm-8">
                           <?= _ent($sungais->klasifikasi); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('sungais_update', function() use ($sungais){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit sungais (Ctrl+e)" href="<?= site_url('administrator/sungais/edit/'.$sungais->kode_sungai); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Sungais']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/sungais/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Sungais']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
