
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Kawasan Kumuh      <small><?= cclang('detail', ['Kawasan Kumuh']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/kawasan_kumuh'); ?>">Kawasan Kumuh</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Kawasan Kumuh</h3>
                     <h5 class="widget-user-desc">Detail Kawasan Kumuh</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_kawasan_kumuh" id="form_kawasan_kumuh" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Kawasan Kumuh </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->kode_kawasan_kumuh); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kawasan Kumuh Id </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->kawasan_kumuh_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tipology </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->tipology); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Luas </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->luas); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Kawasan </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->no_kawasan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Kawas </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->nama_kawas); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kelurahan </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->kelurahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tambahan </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->tambahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kawasan St </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->kawasan_st); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Peruntukan </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->peruntukan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Wilayah Da </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->wilayah_da); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Prioritas </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->prioritas); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tingkat Ke </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->tingkat_ke); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Dampingan </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->dampingan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kab Kota </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->kab_kota); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Objectid </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->objectid); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Kaw </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->nama_kaw); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Luas Kaw </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->luas_kaw); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->kecamatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shape Leng </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->shape_leng); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Shape Area </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->shape_area); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Luas Ha </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->luas_ha); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kawasan Ku </label>

                        <div class="col-sm-8">
                           <?= _ent($kawasan_kumuh->kawasan_ku); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('kawasan_kumuh_update', function() use ($kawasan_kumuh){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit kawasan_kumuh (Ctrl+e)" href="<?= site_url('administrator/kawasan_kumuh/edit/'.$kawasan_kumuh->kode_kawasan_kumuh); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Kawasan Kumuh']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/kawasan_kumuh/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Kawasan Kumuh']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
