
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Kawasan_kumuh/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Kawasan Kumuh<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Kawasan Kumuh</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('kawasan_kumuh_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Kawasan Kumuh']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/kawasan_kumuh/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Kawasan Kumuh']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('kawasan_kumuh_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Kawasan Kumuh" href="<?= site_url('administrator/kawasan_kumuh/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('kawasan_kumuh_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Kawasan Kumuh" href="<?= site_url('administrator/kawasan_kumuh/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Kawasan Kumuh</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Kawasan Kumuh']); ?>  <i class="label bg-yellow"><?= $kawasan_kumuh_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_kawasan_kumuh" id="form_kawasan_kumuh" action="<?= base_url('administrator/kawasan_kumuh/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Kawasan Kumuh Id</th>
                           <th>Tipology</th>
                           <th>Luas</th>
                           <th>No Kawasan</th>
                           <th>Nama Kawas</th>
                           <th>Kelurahan</th>
                           <th>Tambahan</th>
                           <th>Kawasan St</th>
                           <th>Peruntukan</th>
                           <th>Wilayah Da</th>
                           <th>Prioritas</th>
                           <th>Tingkat Ke</th>
                           <th>Dampingan</th>
                           <th>Kab Kota</th>
                           <th>Objectid</th>
                           <th>Nama Kaw</th>
                           <th>Luas Kaw</th>
                           <th>Kecamatan</th>
                           <th>Shape Leng</th>
                           <th>Shape Area</th>
                           <th>Luas Ha</th>
                           <th>Kawasan Ku</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_kawasan_kumuh">
                     <?php foreach($kawasan_kumuhs as $kawasan_kumuh): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $kawasan_kumuh->kode_kawasan_kumuh; ?>">
                           </td>
                           
                           <td><?= _ent($kawasan_kumuh->kawasan_kumuh_id); ?></td> 
                           <td><?= _ent($kawasan_kumuh->tipology); ?></td> 
                           <td><?= _ent($kawasan_kumuh->luas); ?></td> 
                           <td><?= _ent($kawasan_kumuh->no_kawasan); ?></td> 
                           <td><?= _ent($kawasan_kumuh->nama_kawas); ?></td> 
                           <td><?= _ent($kawasan_kumuh->kelurahan); ?></td> 
                           <td><?= _ent($kawasan_kumuh->tambahan); ?></td> 
                           <td><?= _ent($kawasan_kumuh->kawasan_st); ?></td> 
                           <td><?= _ent($kawasan_kumuh->peruntukan); ?></td> 
                           <td><?= _ent($kawasan_kumuh->wilayah_da); ?></td> 
                           <td><?= _ent($kawasan_kumuh->prioritas); ?></td> 
                           <td><?= _ent($kawasan_kumuh->tingkat_ke); ?></td> 
                           <td><?= _ent($kawasan_kumuh->dampingan); ?></td> 
                           <td><?= _ent($kawasan_kumuh->kab_kota); ?></td> 
                           <td><?= _ent($kawasan_kumuh->objectid); ?></td> 
                           <td><?= _ent($kawasan_kumuh->nama_kaw); ?></td> 
                           <td><?= _ent($kawasan_kumuh->luas_kaw); ?></td> 
                           <td><?= _ent($kawasan_kumuh->kecamatan); ?></td> 
                           <td><?= _ent($kawasan_kumuh->shape_leng); ?></td> 
                           <td><?= _ent($kawasan_kumuh->shape_area); ?></td> 
                           <td><?= _ent($kawasan_kumuh->luas_ha); ?></td> 
                           <td><?= _ent($kawasan_kumuh->kawasan_ku); ?></td> 
                           <td width="200">
                              <?php is_allowed('kawasan_kumuh_view', function() use ($kawasan_kumuh){?>
                              <a href="<?= site_url('administrator/kawasan_kumuh/view/' . $kawasan_kumuh->kode_kawasan_kumuh); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('kawasan_kumuh_update', function() use ($kawasan_kumuh){?>
                              <a href="<?= site_url('administrator/kawasan_kumuh/edit/' . $kawasan_kumuh->kode_kawasan_kumuh); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('kawasan_kumuh_delete', function() use ($kawasan_kumuh){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/kawasan_kumuh/delete/' . $kawasan_kumuh->kode_kawasan_kumuh); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($kawasan_kumuh_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Kawasan Kumuh data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'kawasan_kumuh_id' ? 'selected' :''; ?> value="kawasan_kumuh_id">Kawasan Kumuh Id</option>
                           <option <?= $this->input->get('f') == 'tipology' ? 'selected' :''; ?> value="tipology">Tipology</option>
                           <option <?= $this->input->get('f') == 'luas' ? 'selected' :''; ?> value="luas">Luas</option>
                           <option <?= $this->input->get('f') == 'no_kawasan' ? 'selected' :''; ?> value="no_kawasan">No Kawasan</option>
                           <option <?= $this->input->get('f') == 'nama_kawas' ? 'selected' :''; ?> value="nama_kawas">Nama Kawas</option>
                           <option <?= $this->input->get('f') == 'kelurahan' ? 'selected' :''; ?> value="kelurahan">Kelurahan</option>
                           <option <?= $this->input->get('f') == 'tambahan' ? 'selected' :''; ?> value="tambahan">Tambahan</option>
                           <option <?= $this->input->get('f') == 'kawasan_st' ? 'selected' :''; ?> value="kawasan_st">Kawasan St</option>
                           <option <?= $this->input->get('f') == 'peruntukan' ? 'selected' :''; ?> value="peruntukan">Peruntukan</option>
                           <option <?= $this->input->get('f') == 'wilayah_da' ? 'selected' :''; ?> value="wilayah_da">Wilayah Da</option>
                           <option <?= $this->input->get('f') == 'prioritas' ? 'selected' :''; ?> value="prioritas">Prioritas</option>
                           <option <?= $this->input->get('f') == 'tingkat_ke' ? 'selected' :''; ?> value="tingkat_ke">Tingkat Ke</option>
                           <option <?= $this->input->get('f') == 'dampingan' ? 'selected' :''; ?> value="dampingan">Dampingan</option>
                           <option <?= $this->input->get('f') == 'kab_kota' ? 'selected' :''; ?> value="kab_kota">Kab Kota</option>
                           <option <?= $this->input->get('f') == 'objectid' ? 'selected' :''; ?> value="objectid">Objectid</option>
                           <option <?= $this->input->get('f') == 'nama_kaw' ? 'selected' :''; ?> value="nama_kaw">Nama Kaw</option>
                           <option <?= $this->input->get('f') == 'luas_kaw' ? 'selected' :''; ?> value="luas_kaw">Luas Kaw</option>
                           <option <?= $this->input->get('f') == 'kecamatan' ? 'selected' :''; ?> value="kecamatan">Kecamatan</option>
                           <option <?= $this->input->get('f') == 'shape_leng' ? 'selected' :''; ?> value="shape_leng">Shape Leng</option>
                           <option <?= $this->input->get('f') == 'shape_area' ? 'selected' :''; ?> value="shape_area">Shape Area</option>
                           <option <?= $this->input->get('f') == 'luas_ha' ? 'selected' :''; ?> value="luas_ha">Luas Ha</option>
                           <option <?= $this->input->get('f') == 'kawasan_ku' ? 'selected' :''; ?> value="kawasan_ku">Kawasan Ku</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/kawasan_kumuh');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_kawasan_kumuh').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/kawasan_kumuh/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>