
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Jembatan_pt_250k/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Jembatan Pt 250k<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Jembatan Pt 250k</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('jembatan_pt_250k_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Jembatan Pt 250k']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/jembatan_pt_250k/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Jembatan Pt 250k']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('jembatan_pt_250k_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Jembatan Pt 250k" href="<?= site_url('administrator/jembatan_pt_250k/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('jembatan_pt_250k_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Jembatan Pt 250k" href="<?= site_url('administrator/jembatan_pt_250k/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Jembatan Pt 250k</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Jembatan Pt 250k']); ?>  <i class="label bg-yellow"><?= $jembatan_pt_250k_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_jembatan_pt_250k" id="form_jembatan_pt_250k" action="<?= base_url('administrator/jembatan_pt_250k/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Jembatan Id</th>
                           <th>Field1-field18</th>
                           <th>Filed2</th>
                           <th>Filed3</th>
                           <th>Filed4</th>
                           <th>Filed5</th>
                           <th>Filed6</th>
                           <th>Filed7</th>
                           <th>Filed8</th>
                           <th>Filed9</th>
                           <th>Filed10</th>
                           <th>Filed11</th>
                           <th>Filed12</th>
                           <th>Filed13</th>
                           <th>Filed14</th>
                           <th>Filed15</th>
                           <th>Filed16</th>
                           <th>Filed17</th>
                           <th>Filed18</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_jembatan_pt_250k">
                     <?php foreach($jembatan_pt_250ks as $jembatan_pt_250k): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $jembatan_pt_250k->kode_jpt; ?>">
                           </td>
                           
                           <td><?= _ent($jembatan_pt_250k->jembatan_id); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->field1-field18); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed2); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed3); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed4); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed5); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed6); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed7); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed8); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed9); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed10); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed11); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed12); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed13); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed14); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed15); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed16); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed17); ?></td> 
                           <td><?= _ent($jembatan_pt_250k->filed18); ?></td> 
                           <td width="200">
                              <?php is_allowed('jembatan_pt_250k_view', function() use ($jembatan_pt_250k){?>
                              <a href="<?= site_url('administrator/jembatan_pt_250k/view/' . $jembatan_pt_250k->kode_jpt); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('jembatan_pt_250k_update', function() use ($jembatan_pt_250k){?>
                              <a href="<?= site_url('administrator/jembatan_pt_250k/edit/' . $jembatan_pt_250k->kode_jpt); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('jembatan_pt_250k_delete', function() use ($jembatan_pt_250k){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/jembatan_pt_250k/delete/' . $jembatan_pt_250k->kode_jpt); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($jembatan_pt_250k_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Jembatan Pt 250k data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'jembatan_id' ? 'selected' :''; ?> value="jembatan_id">Jembatan Id</option>
                           <option <?= $this->input->get('f') == 'field1-field18' ? 'selected' :''; ?> value="field1-field18">Field1-field18</option>
                           <option <?= $this->input->get('f') == 'filed2' ? 'selected' :''; ?> value="filed2">Filed2</option>
                           <option <?= $this->input->get('f') == 'filed3' ? 'selected' :''; ?> value="filed3">Filed3</option>
                           <option <?= $this->input->get('f') == 'filed4' ? 'selected' :''; ?> value="filed4">Filed4</option>
                           <option <?= $this->input->get('f') == 'filed5' ? 'selected' :''; ?> value="filed5">Filed5</option>
                           <option <?= $this->input->get('f') == 'filed6' ? 'selected' :''; ?> value="filed6">Filed6</option>
                           <option <?= $this->input->get('f') == 'filed7' ? 'selected' :''; ?> value="filed7">Filed7</option>
                           <option <?= $this->input->get('f') == 'filed8' ? 'selected' :''; ?> value="filed8">Filed8</option>
                           <option <?= $this->input->get('f') == 'filed9' ? 'selected' :''; ?> value="filed9">Filed9</option>
                           <option <?= $this->input->get('f') == 'filed10' ? 'selected' :''; ?> value="filed10">Filed10</option>
                           <option <?= $this->input->get('f') == 'filed11' ? 'selected' :''; ?> value="filed11">Filed11</option>
                           <option <?= $this->input->get('f') == 'filed12' ? 'selected' :''; ?> value="filed12">Filed12</option>
                           <option <?= $this->input->get('f') == 'filed13' ? 'selected' :''; ?> value="filed13">Filed13</option>
                           <option <?= $this->input->get('f') == 'filed14' ? 'selected' :''; ?> value="filed14">Filed14</option>
                           <option <?= $this->input->get('f') == 'filed15' ? 'selected' :''; ?> value="filed15">Filed15</option>
                           <option <?= $this->input->get('f') == 'filed16' ? 'selected' :''; ?> value="filed16">Filed16</option>
                           <option <?= $this->input->get('f') == 'filed17' ? 'selected' :''; ?> value="filed17">Filed17</option>
                           <option <?= $this->input->get('f') == 'filed18' ? 'selected' :''; ?> value="filed18">Filed18</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/jembatan_pt_250k');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_jembatan_pt_250k').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/jembatan_pt_250k/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>