
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Jembatan Pt 250k      <small><?= cclang('detail', ['Jembatan Pt 250k']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/jembatan_pt_250k'); ?>">Jembatan Pt 250k</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Jembatan Pt 250k</h3>
                     <h5 class="widget-user-desc">Detail Jembatan Pt 250k</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_jembatan_pt_250k" id="form_jembatan_pt_250k" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Jpt </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->kode_jpt); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jembatan Id </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->jembatan_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field1-field18 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->field1-field18); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed2 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed3 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed4 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed5 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed6 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed6); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed7 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed7); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed8 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed8); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed9 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed9); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed10 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed10); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed11 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed11); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed12 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed12); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed13 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed13); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed14 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed14); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed15 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed15); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed16 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed16); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed17 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed17); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Filed18 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan_pt_250k->filed18); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('jembatan_pt_250k_update', function() use ($jembatan_pt_250k){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit jembatan_pt_250k (Ctrl+e)" href="<?= site_url('administrator/jembatan_pt_250k/edit/'.$jembatan_pt_250k->kode_jpt); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Jembatan Pt 250k']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/jembatan_pt_250k/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Jembatan Pt 250k']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
