
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Jembatan      <small><?= cclang('detail', ['Jembatan']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/jembatan'); ?>">Jembatan</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Jembatan</h3>
                     <h5 class="widget-user-desc">Detail Jembatan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_jembatan" id="form_jembatan" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Jpt </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->kode_jpt); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jembatan Id </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->jembatan_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field1 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field2 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field3 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field4 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Jembatan </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field6 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field6); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field7 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field7); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field8 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field8); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field9 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field9); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field10 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field10); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field11 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field11); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field12 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field12); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field13 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field13); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field14 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field14); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field15 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field15); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field16 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field16); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field17 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field17); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Field18 </label>

                        <div class="col-sm-8">
                           <?= _ent($jembatan->field18); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('jembatan_update', function() use ($jembatan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit jembatan (Ctrl+e)" href="<?= site_url('administrator/jembatan/edit/'.$jembatan->kode_jpt); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Jembatan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/jembatan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Jembatan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
